/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./views/**/*.blade.php",
    "./public/**/*.php",
    "./src/**/*.php",
    "./data/**/*.json"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch Design System palette
        "surface-cream-light": "#FBF8F3",
        "surface-cream-warm": "#F1D6A9",
        "surface-pure": "#FFFFFF",
        "surface-bright": "#f9f9ff",
        "surface-dim": "#cfdaf2",
        "surface-container": "#e7eeff",
        "surface-container-high": "#dee8ff",
        "surface-container-highest": "#d8e3fb",
        "surface-container-low": "#f0f3ff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#bb1900",
        "on-surface": "#111c2d",
        "on-surface-variant": "#5d3f3a",
        "inverse-surface": "#263143",
        "inverse-on-surface": "#ecf1ff",
        "inverse-primary": "#ffb4a6",
        "primary": "#b61800",
        "primary-container": "#e22708",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdad3",
        "primary-fixed-dim": "#ffb4a6",
        "on-primary-fixed": "#3f0300",
        "on-primary-fixed-variant": "#8f1100",
        "secondary": "#a83900",
        "secondary-container": "#fc6c2f",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5b1b00",
        "secondary-fixed": "#ffdbcf",
        "secondary-fixed-dim": "#ffb59a",
        "on-secondary-fixed": "#380d00",
        "on-secondary-fixed-variant": "#812900",
        "tertiary": "#894d15",
        "tertiary-container": "#a7652b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdcc4",
        "tertiary-fixed-dim": "#ffb77f",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-fixed-variant": "#6f3900",
        "outline": "#926f68",
        "outline-variant": "#e7bdb5",
        "text-muted": "#64748B",
        "live-badge": "#F43517",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        // Retro-compatibility with existing views
        ibnp: {
          primary: '#F43517',
          secondary: '#F36529',
          accent: '#EFA162',
          surface: '#F1D6A9',
          dark: '#1E293B',
          light: '#FFFFFF',
          gray: {
            50: '#F8FAFC',
            100: '#F1F5F9',
            200: '#E2E8F0',
            300: '#CBD5E1',
            400: '#94A3B8',
            500: '#64748B',
            600: '#475569',
            700: '#334155',
            800: '#1E293B',
            900: '#0F172A'
          }
        }
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        serif: ['Merriweather', 'Georgia', 'serif']
      },
      fontSize: {
        "display-lg": ["3.5rem", { "lineHeight": "1.15", "letterSpacing": "-0.025em", "fontWeight": "800" }],
        "display-lg-mobile": ["2.25rem", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg": ["2.25rem", { "lineHeight": "1.25", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["1.75rem", { "lineHeight": "1.3", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "headline-md": ["1.5rem", { "lineHeight": "1.35", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-sm": ["1.25rem", { "lineHeight": "1.4", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "label-lg": ["1rem", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "label-md": ["0.875rem", { "lineHeight": "1.4", "letterSpacing": "0.015em", "fontWeight": "600" }],
        "label-sm": ["0.75rem", { "lineHeight": "1.3", "letterSpacing": "0.04em", "fontWeight": "700" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.65", "fontWeight": "400" }],
        "body-md": ["1rem", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.5", "fontWeight": "400" }]
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "3rem",
        "margin-mobile": "1.25rem"
      }
    },
  },
  plugins: [],
}
